language: scala
sudo: required
services:
  - docker
scala:
  - 2.12.8
  - 2.13.0
before_install:
  - git submodule update --init --recursive
  - sh src/test/docker-cups-pdf/build.sh
  - sh src/test/docker-cups-pdf/run.sh
script:
  - sbt test:compile test
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.ivy2
